In [3]:
import numpy as np

In [4]:
A_val=np.array([1,2,3,4])

In [5]:
B_val=np.array([100,200,300,400])

In [6]:
condition=np.array([True,False,True,False])

In [7]:
np.where(condition,A_val,B_val)

array([  1, 200,   3, 400])

In [8]:
from numpy.random import randn

In [9]:
arr=randn(5,5)
arr

array([[-0.0615136 , -1.03592302,  0.10626887, -0.27811796,  0.42862487],
       [-0.60767366, -0.88778252, -1.08878277, -1.21893141,  1.46774619],
       [ 0.58073399, -0.0032018 ,  1.02360866,  0.69506701,  0.3094628 ],
       [ 0.40650718, -0.3200843 , -0.49020158, -0.9033324 ,  1.03573086],
       [ 0.15606111,  0.56446516, -0.72805594,  1.18147368, -1.27650564]])

In [10]:
np.where(arr<0,0,arr)

array([[0.        , 0.        , 0.10626887, 0.        , 0.42862487],
       [0.        , 0.        , 0.        , 0.        , 1.46774619],
       [0.58073399, 0.        , 1.02360866, 0.69506701, 0.3094628 ],
       [0.40650718, 0.        , 0.        , 0.        , 1.03573086],
       [0.15606111, 0.56446516, 0.        , 1.18147368, 0.        ]])

In [11]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr.sum()

45

In [14]:
arr.sum(0)

array([12, 15, 18])

In [15]:
arr.sum(1)

array([ 6, 15, 24])

In [16]:
arr.mean()

5.0

In [17]:
arr.std()

2.581988897471611

In [18]:
arr.var()

6.666666666666667

In [22]:
bool_arr=np.array([True,False,True])

In [23]:
bool_arr.any()

True

In [24]:
bool_arr.all()

False

In [25]:
arr=randn(5)
arr

array([-0.34536407, -0.43921331,  0.91468702, -0.72994279, -0.16574098])

In [28]:
arr.sort()
arr

array([-0.72994279, -0.43921331, -0.34536407, -0.16574098,  0.91468702])

In [27]:
arr2=np.array(['a','b','c','d','e','b','a'])
arr2

array(['a', 'b', 'c', 'd', 'e', 'b', 'a'], dtype='<U1')

In [29]:
np.unique(arr2)

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [31]:
np.in1d(['c','e','z'],arr2)

array([ True,  True, False])