In [1]:
import numpy as np

In [2]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
np.save('my arr',arr)

In [4]:
!pip list

Package                            Version   
---------------------------------- ----------
alabaster                          0.7.12    
anaconda-client                    1.7.2     
anaconda-navigator                 1.9.6     
anaconda-project                   0.8.2     
asn1crypto                         0.24.0    
astroid                            2.1.0     
astropy                            3.1       
atomicwrites                       1.2.1     
attrs                              18.2.0    
Babel                              2.6.0     
backcall                           0.1.0     
backports.os                       0.1.1     
backports.shutil-get-terminal-size 1.0.0     
beautifulsoup4                     4.6.3     
bitarray                           0.8.3     
bkcharts                           0.2       
blaze                              0.11.3    
bleach                             3.0.2     
bokeh                              1.0.2     
boto                              

In [5]:
!pip install pyttsx3

  Using cached https://files.pythonhosted.org/packages/12/b4/75d792acf44c01200690030f185e246244ebdfc12db84690e5c1c4df2864/pyttsx3-2.7-py3-none-any.whl


In [6]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr1=np.load('my arr.npy')
arr1

array([0, 1, 2, 3, 4])

In [8]:
arr2=arr

In [10]:
np.savez('ziparray.npz',x=arr1,y=arr2)

In [11]:
archive_array=np.load('ziparray.npz')

In [12]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [13]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
archive_array.keys()

KeysView(<numpy.lib.npyio.NpzFile object at 0x0000022E7E0D54E0>)

In [16]:
[key for key in archive_array.keys()]

['x', 'y']

In [17]:
[value for value in archive_array.values()]

[array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [18]:
[item for item in archive_array.items()]

[('x', array([0, 1, 2, 3, 4])), ('y', array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))]

In [19]:
import numpy as np

In [20]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.savetxt('textarray.txt',arr,delimiter=',')

In [22]:
arr1=np.loadtxt('textarray.txt',delimiter=',')
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])