In [1]:
import numpy as np

In [3]:
L1=[1,2,3,4]
L1

[1, 2, 3, 4]

In [4]:
arr1=np.array(L1)
arr1

array([1, 2, 3, 4])

In [5]:
L2=[11,22,33,44]
L2

[11, 22, 33, 44]

In [9]:
arr2=np.array(L2)
arr2

array([11, 22, 33, 44])

In [11]:
L3=[L1,L3]

NameError: name 'L3' is not defined

In [12]:
arr2.shape

(4,)

In [13]:
arr1.shape

(4,)

In [15]:
arr2.dtype

dtype('int32')

In [20]:
zero_arr=np.zeros(5)
zero_arr

array([0., 0., 0., 0., 0.])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.eye()