In [8]:
import cv2

In [9]:
imgpath='G:\\Photos\College Friends\Galta Ji\\IMG_20180831_222459049.jpg'

In [10]:
img=cv2.imread(imgpath)
img1=cv2.imread(imgpath)

In [11]:
outpath='G:\\Photos\\College Friends\\img1.jpg'

In [12]:
print(img)

[[[ 36  91  98]
  [ 31  83  90]
  [ 33  73  85]
  ...
  [ 29  29  29]
  [ 29  29  29]
  [ 29  29  29]]

 [[ 26  78  85]
  [ 31  78  86]
  [ 27  67  79]
  ...
  [ 29  29  29]
  [ 29  29  29]
  [ 29  29  29]]

 [[ 29  70  79]
  [ 29  70  79]
  [ 30  70  82]
  ...
  [ 29  29  29]
  [ 29  29  29]
  [ 29  29  29]]

 ...

 [[ 31  50  93]
  [ 31  53  95]
  [ 30  52  93]
  ...
  [ 44  66  84]
  [ 42  64  82]
  [ 39  61  79]]

 [[ 33  54  99]
  [ 32  56  98]
  [ 30  55  95]
  ...
  [ 41  64  80]
  [ 39  62  78]
  [ 35  58  74]]

 [[ 32  55 100]
  [ 32  56  98]
  [ 27  52  94]
  ...
  [ 43  66  82]
  [ 43  66  82]
  [ 37  60  76]]]


In [13]:
print(type(img))

<class 'numpy.ndarray'>


In [14]:
print(img.dtype)
print(img.shape)
print(img.ndim)
print(img.size)

uint8
(592, 1040, 3)
3
1847040


In [15]:
cv2.imshow('My Image',img)
cv2.imshow('Color Image',img)
cv2.imshow('Gray img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

cv2.destroyWindows('Gray Img')




AttributeError: module 'cv2.cv2' has no attribute 'destroyWindows'