In [1]:
import numpy as np
from pandas import DataFrame
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [77]:
x=np.array([[1,2],[2,3],[4,5],[6,7],[8,9],[10,11]])
x

array([[ 1,  2],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [91]:
y=np.array([64,169,529,1089,1849,2809])# sqare of every y or #y=(2x1+3x2)**2
y


array([  64,  169,  529, 1089, 1849, 2809])

In [92]:
lreg=LinearRegression()#training
lreg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [93]:
lreg.predict(np.array([[144,169]]))

array([46469.1369863])

In [94]:
x_train,x_test,y_train,y_test=train_test_split(x,y)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[ 4  5]
 [10 11]
 [ 1  2]
 [ 6  7]]
[[8 9]
 [2 3]]
[ 529 2809   64 1089]
[1849  169]


In [95]:
lreg=LinearRegression()
lreg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [96]:
test_predict=lreg.predict(x_test)
test_predict

array([1973.56140351,  117.24561404])

In [97]:
train_predict=lreg.predict(x_train)
train_predict

array([ 736.01754386, 2592.33333333, -192.14035088, 1354.78947368])

In [98]:
pd.concat([DataFrame(y_train,columns=['Train Data']),DataFrame(train_predict,columns=['Train Pred'])],axis=1)

Train Data   Train Pred
0         529   736.017544
1        2809  2592.333333
2          64  -192.140351
3        1089  1354.789474

In [99]:
print('RMSE',np.sqrt(np.mean((y_train-train_predict)**2)))

RMSE 237.7249627084561
