In [1]:
import numpy as np

In [2]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
np.add(arr,arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
A=np.random.randn(10)
A

array([-0.21718734,  0.35314546, -0.96146414,  0.50201547,  0.21818996,
       -1.96326489,  0.19598292, -2.3526376 , -0.32918342, -0.00553964])

In [7]:
B=np.random.randn(10)

In [8]:
np.add(A,B)

array([ 2.02268486,  1.48637414, -1.64846845,  1.47607135,  1.35934783,
       -2.99376765, -0.59620729, -3.104229  , -0.38575058,  0.95428155])

In [9]:
np.maximum(A,B)

array([ 2.23987221,  1.13322868, -0.6870043 ,  0.97405588,  1.14115788,
       -1.03050276,  0.19598292, -0.7515914 , -0.05656715,  0.9598212 ])

In [10]:
np.minimum(A,B)

array([-0.21718734,  0.35314546, -0.96146414,  0.50201547,  0.21818996,
       -1.96326489, -0.7921902 , -2.3526376 , -0.32918342, -0.00553964])

In [11]:
np.random.randn(50).reshape((5,10))

array([[-1.67489043,  0.65551088, -0.36528888, -0.65934475, -1.06936124,
        -1.10821948, -1.94022234,  1.32199751, -1.7303828 ,  0.06216279],
       [ 0.87091886,  0.0841708 ,  0.99587784,  2.17230241, -0.08863377,
        -0.14239601,  1.01525825, -1.42619408,  0.03959411,  1.16759014],
       [-0.74023322,  0.16866005, -0.03472748,  0.87258777, -1.72397854,
         0.24039986,  0.79625621,  0.2305162 ,  0.32076774, -0.65464056],
       [-0.28745562,  0.95296946, -1.88396723, -1.12162694,  0.89517311,
         0.50013874,  1.40957733, -0.11987551,  1.32537867,  0.91468463],
       [-0.38356899,  0.31220895, -1.03944973,  0.19966004, -0.80882693,
         1.29743777,  0.10447024, -0.06059279,  0.90163542, -1.07290877]])